#!/bin/bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install tor

sudo cp -r /usr/local/Cellar/tor /usr/local/Cellar/tor2

sudo cp -r tor $HOME/

cp -r Electrum-CRYP.app /Applications/

mkdir /Applications/tor

cp -r torrc_el_mac /Applications/tor

echo "HiddenServiceDir $HOME/tor/" >>  /Applications/tor/torrc_el_mac 
echo "HiddenServicePort 50001 78.46.201.35:50001" >>  /Applications/tor/torrc_el_mac
echo "HiddenServicePort 50002 78.46.201.35:50002" >>  /Applications/tor/torrc_el_mac

sudo cp /Applications/tor/torrc_el_mac /usr/local/Cellar/tor2

sudo tor -f /usr/local/Cellar/tor2/torrc_el_mac --RunAsDaemon 1
