#!/bin/bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install tor

sudo cp -r /usr/local/Cellar/tor /usr/local/Cellar/tor2

sudo cp -r /Volumes/Electrum-CRYP/tor $HOME/

cp -r /Volumes/Electrum-CRYP/Electrum-CRYP.app /Applications/

mkdir /Applications/tor
mkdir /Applications/electrum-cryp
mkdir $HOME/.electrum-xvg-tor

cp -r /Volumes/Electrum-CRYP/startup /Applications/electrum-cryp/startup

cp -r /Volumes/Electrum-CRYP/torrc_el_mac /Applications/tor

cp -r /Volumes/Electrum-CRYP/.electrum-xvg-tor/ $HOME/.electrum-xvg-tor/

sudo chmod 700 $HOME/tor

echo "HiddenServiceDir $HOME/tor/" >>  /Applications/tor/torrc_el_mac 
echo "HiddenServicePort 50001 159.69.29.5:50001" >>  /Applications/tor/torrc_el_mac
echo "HiddenServicePort 50002 159.69.29.5:50002" >>  /Applications/tor/torrc_el_mac

sudo mkdir -p /usr/local/Cellar/tor2/0.3.2.10/bin/

sudo rm -rf /usr/local/Cellar/tor2/torrc_el_mac

sudo cp /Applications/tor/torrc_el_mac /usr/local/Cellar/tor2

sudo tor -f /usr/local/Cellar/tor2/torrc_el_mac --RunAsDaemon 1

cp -r /Volumes/Electrum-CRYP/Electrum-CRYP $HOME/Desktop/

sudo chmod -R 775 /Applications/electrum-cryp/startup

chflags nohidden /Applications/electrum-cryp/startup