#!/bin/bash

sudo killall tor

sudo rm -rf $HOME/.electrum-xvg-tor/blockchain_headers

sudo tor -f /usr/local/Cellar/tor2/torrc_el_mac --RunAsDaemon 1

chmod +x /Applications/Electrum-CRYP.app/Contents/MacOS/Electrum-CRYP

sudo /Applications/Electrum-CRYP.app/Contents/MacOS/Electrum-CRYP
